### PR TITLE
a default 3d sprite?

### PR DESCRIPTION
**Pull request by pedropsi**
I think having a default 3d sprite could be useful so people see immediately how to use the fork?

### CODE REVIEW

**Comment by m-ender** [comment]
Wow, how did I miss this PR. I even noticed that you forked the project and made those changes on your side, but I somehow didn't get notified for the PR.

I think I might actually add an additional section of examples to showcase the different features of this fork, but I'll keep the PR around to remind myself. :)

**Comment by m-ender** [comment]
Oh I see, this isn't for the samples but for the default game. Is there any way to bring that up again, other than visiting the page in a new browser/incognito mode?

**Comment by m-ender** [comment]
Alright, I've added a pseudo-3D rework of the basic example to the list of example games. I think I prefer that over complicating the default game. Thanks a lot for the suggestion though, I really appreciate it. :)

**Comment by ghost** [comment]
A full example game works too, of course :)

**Pull request closed without merging**
